name: sistema-rifas-pampero
static_sites:
- build_command: echo "Static site - no build needed"
  environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: TU-USUARIO/sistema-rifas-pampero
  name: frontend
  routes:
  - path: /
  source_dir: /
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
envs:
- key: SUPABASE_URL
  scope: RUN_TIME
  value: https://tu-proyecto.supabase.co
- key: SUPABASE_ANON_KEY
  scope: RUN_TIME
  value: tu-supabase-anon-key