# Digital Ocean App Platform Configuration
name: pampero-rifas
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/pampero-rifas
    branch: main
  run_command: echo "Aplicación estática lista"
  build_command: node inject-env.js
  environment_slug: html
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 80
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: SUPABASE_URL
    scope: BUILD_AND_RUN
    type: SECRET
  - key: SUPABASE_ANON_KEY
    scope: BUILD_AND_RUN
    type: SECRET
