# 🌊 Configuración STATIC SITE para Digital Ocean App Platform

name: pampero-rifas
static_sites:
- name: web
  build_command: node inject-env.js
  output_dir: /
  index_document: index.html
  error_document: index.html
  catchall_document: index.html
  envs:
  - key: SUPABASE_URL
    scope: BUILD_TIME
    type: SECRET
  - key: SUPABASE_ANON_KEY
    scope: BUILD_TIME
    type: SECRET
