# .do/app.yaml - Configuración para Digital Ocean App Platform
name: rifas-pampero
services:
- name: web
  source_dir: /
  github:
    repo: tu-usuario/rifas-pampero
    branch: main
  run_command: |
    echo "🚀 Iniciando build para Rifas Pampero..."
    chmod +x build.sh
    ./build.sh
    echo "🎉 Build completado, sirviendo aplicación..."
    python3 -m http.server 8080
  environment_slug: static
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  # Variables de Supabase
  - key: SUPABASE_URL
    value: "${SUPABASE_URL}"
    type: SECRET
  - key: SUPABASE_ANON_KEY
    value: "${SUPABASE_ANON_KEY}"
    type: SECRET
  
  # Variables de Google APIs
  - key: GOOGLE_CLIENT_ID
    value: "${GOOGLE_CLIENT_ID}"
    type: SECRET
  - key: GOOGLE_API_KEY
    value: "${GOOGLE_API_KEY}"
    type: SECRET
  
  # Configuración de la Rifa
  - key: RAFFLE_NAME
    value: "${RAFFLE_NAME}"
  - key: RAFFLE_ORGANIZATION
    value: "${RAFFLE_ORGANIZATION}"
  - key: RAFFLE_DRAW_DATE
    value: "${RAFFLE_DRAW_DATE}"
  - key: RAFFLE_PRIZE
    value: "${RAFFLE_PRIZE}"
  - key: RAFFLE_OBJECTIVE
    value: "${RAFFLE_OBJECTIVE}"
  - key: RAFFLE_TOTAL_NUMBERS
    value: "${RAFFLE_TOTAL_NUMBERS}"
  - key: RAFFLE_PRICE_PER_NUMBER
    value: "${RAFFLE_PRICE_PER_NUMBER}"
  - key: RAFFLE_WHATSAPP_NUMBER
    value: "${RAFFLE_WHATSAPP_NUMBER}"
  - key: RAFFLE_RESERVATION_TIME
    value: "${RAFFLE_RESERVATION_TIME}"
  - key: RAFFLE_CLUB_INSTAGRAM
    value: "${RAFFLE_CLUB_INSTAGRAM}"
  
  # Variables de pago
  - key: PAYMENT_MP_ALIAS
    value: "${PAYMENT_MP_ALIAS}"
  - key: PAYMENT_MP_CVU
    value: "${PAYMENT_MP_CVU}"
  - key: PAYMENT_MP_HOLDER
    value: "${PAYMENT_MP_HOLDER}"
  - key: PAYMENT_MP_CUIT
    value: "${PAYMENT_MP_CUIT}"

  routes:
  - path: /
  cors:
    allow_origins:
    - exact: https://ssmpnzcjhrjqhglqkmoe.supabase.co